{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "virbius.secretName" . }}
  labels:
    {{- include "virbius.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.secrets.mysqlRootPassword | quote }}
  mysql-password: {{ .Values.secrets.mysqlPassword | quote }}
  license-master-key: {{ .Values.secrets.licenseMasterKey | quote }}
  deepseek-api-key: {{ .Values.secrets.deepseekApiKey | quote }}
  openrouter-api-key: {{ .Values.secrets.openrouterApiKey | quote }}
{{- end }}
