package io.virbius.control.domain;

import java.time.Instant;
import java.util.List;

/**
 * A compiled prompt template for a specific scene + constitution version.
 *
 * <p>Generated by {@code ConstitutionCompiler} from active {@link ConstitutionRule}
 * entries. The edge layer ({@code PromptGateway}) caches these templates and
 * uses them to augment system prompts before sending to the LLM.
 *
 * @param systemPrefix  prepended to the system message — contains prohibitions,
 *                      tool rules, and principles rendered as text
 * @param dynamicSuffix appended to the system message — contains template
 *                      variables ({{risk_score}}, {{recent_tools}}, etc.)
 *                      that are filled at runtime
 * @param prohibitions  list of prohibition strings (for structured access)
 * @param toolRules     list of tool rule strings (for structured access)
 */
public record ConstitutionTemplate(
        Long id,
        String tenantId,
        String constitutionVersion,
        String scene,
        String systemPrefix,
        String dynamicSuffix,
        List<String> prohibitions,
        List<String> toolRules,
        Instant compiledAt) {

    /** Wildcard scene — used as fallback when no scene-specific template exists. */
    public static final String SCENE_WILDCARD = "*";
}
