-- Constitution rules for Prompt Gateway (§2.8).
-- Each rule is a clause that gets compiled into scene-specific prompt templates.
CREATE TABLE IF NOT EXISTS tb_constitution (
    id              INTEGER PRIMARY KEY,
    tenant_id       VARCHAR(64)  NOT NULL,
    rule_id         VARCHAR(128) NOT NULL,
    version         VARCHAR(32)  NOT NULL DEFAULT '1.0',
    category        VARCHAR(64)  NOT NULL,          -- prohibition | tool_rule | boundary | principle
    priority        INTEGER      NOT NULL DEFAULT 50, -- higher = earlier in template
    scene_filter    TEXT         NOT NULL DEFAULT '[]', -- JSON array of scene names, empty = all scenes
    rule_text       TEXT         NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'active', -- active | disabled
    created_by      VARCHAR(64),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, rule_id, version),
    CHECK (category IN ('prohibition', 'tool_rule', 'boundary', 'principle')),
    CHECK (status IN ('active', 'disabled')),
    CHECK (priority >= 0 AND priority <= 100)
);

CREATE INDEX IF NOT EXISTS idx_tb_constitution_tenant_scene
    ON tb_constitution (tenant_id, status);

-- Compiled prompt templates per scene + constitution version.
-- Generated by virbius-compiler from tb_constitution rows.
CREATE TABLE IF NOT EXISTS tb_constitution_templates (
    id              INTEGER PRIMARY KEY,
    tenant_id       VARCHAR(64)  NOT NULL,
    constitution_version VARCHAR(32) NOT NULL,
    scene           VARCHAR(64)  NOT NULL,            -- scene name, or '*' for default
    system_prefix   TEXT         NOT NULL,            -- prepended to system message
    dynamic_suffix  TEXT         NOT NULL DEFAULT '', -- appended to system message (template variables)
    prohibitions    TEXT         NOT NULL DEFAULT '[]', -- JSON array of prohibition strings
    tool_rules      TEXT         NOT NULL DEFAULT '[]', -- JSON array of tool rule strings
    compiled_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, constitution_version, scene)
);

CREATE INDEX IF NOT EXISTS idx_tb_constitution_templates_lookup
    ON tb_constitution_templates (tenant_id, scene, constitution_version);
