-- Agent filing information: name, description, and standardized AID (GB/Z 185.2).
-- The AID is auto-generated by the application on license issue.

ALTER TABLE tb_agent_licenses
    ADD COLUMN agent_name   VARCHAR(256) NOT NULL DEFAULT '',
    ADD COLUMN description  TEXT         NOT NULL DEFAULT '',
    ADD COLUMN agent_aid    VARCHAR(256) NOT NULL DEFAULT '';

CREATE INDEX idx_tb_agent_licenses_aid
    ON tb_agent_licenses (agent_aid);
